baseURL: http://wlchn.github.io/
languageCode: en-us
title: Lei Wang
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archives
          url: /archives
          weight: 1
        - name: Search
          url: /search
          weight: 2
        - name: Github
          url: https://github.com/wlchn
          weight: 3

params:
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      I'm Lei Wang, a full-stack developer.
  socialIcons:
    - name: email
      url: "mailto:geekwanglei@gmail.com"
    # - name: linkedin
    #  url: "https://linkedin.com/in/wlchn"
    - name: github
      url: "https://github.com/wlchn"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/5184758/lei-wang"
    - name: twitter
      url: "https://twitter.com/wlchn"
